### ISSUE TITLE
Technical review: meta issue 

### ISSUE THREAD

**Issue by Revathyvenugopal162** [ansys/pyansys-heart#521]
- [x] Update the precommit
- [ ] Move ansys/heart -> src/ansys/heart
- [ ] Update the ci/cd
- [ ] update src code and version file
- [x] improve logger
- [x] improve readme
- [x] add necessary file
- [x] remove unwanted file
- [x] Add the licence header
- [x] fix documentation
- [ ]
